name: backend-commit-stage

on:
  push:
    branches: [ "main" ]
    paths:
        - 'backend/**'
        - '.github/workflows/backend-commit-stage.yml'
  pull_request:
    branches: [ "main" ]
    paths:
        - 'backend/**'
        - '.github/workflows/backend-commit-stage.yml'
  workflow_dispatch:

concurrency:
  group: commit-stage-backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest

    outputs:
      image-digest-url: ${{ steps.push.outputs.image-digest-url }}

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Runtime
      uses: optivem/actions/setup-java-gradle@v1
      with:
        java-version: 21
        working-directory: backend

    - name: Compile Code
      run: ./gradlew build
      working-directory: backend

    # - name: Run Unit Tests
    # - name: Run Narrow Integration Tests
    # - name: Run Component Tests
    # - name: Run Contract Tests
    # - name: Run Linter
    # - name: Run Code Analysis

    - name: Build Artifact
      if: github.ref == 'refs/heads/main'
      id: build
      uses: optivem/actions/build-docker-image@v1
      with:
        working-directory: backend
        image-name: backend
        image-namespace: ${{ github.repository }}
        commit-sha: ${{ github.sha }}
        dockerfile: Dockerfile

    - name: Push Artifact
      if: github.ref == 'refs/heads/main'
      id: push
      uses: optivem/actions/push-docker-image@v1
      with:
        image-sha-tag: ${{ steps.build.outputs.image-sha-tag }}
        image-latest-url: ${{ steps.build.outputs.image-latest-url }}
        registry-username: ${{ github.actor }}
      env:
        REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  summary:
    needs: run
    if: always()
    runs-on: ubuntu-latest

    steps:

    - name: Summarize Commit Stage
      uses: optivem/actions/summarize-commit-stage@v1
      with:
        stage-result: ${{ needs.run.result }}
        success-artifact-url: ${{ needs.run.outputs.image-digest-url }}
