name: backend-commit-stage

on:
  push:
    branches: [ "main" ]
    paths:
        - 'backend/**'
        - '.github/workflows/backend-commit-stage.yml'
  pull_request:
    branches: [ "main" ]
    paths:
        - 'backend/**'
        - '.github/workflows/backend-commit-stage.yml'
  workflow_dispatch:

concurrency:
  group: commit-stage-backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image-digest-url: ${{ steps.publish.outputs.image-digest-url }}
      image-created-timestamp: ${{ steps.publish.outputs.image-created-timestamp }}

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Runtime
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Make Gradle Wrapper executable
      run: chmod +x ./gradlew
      shell: bash
      working-directory: backend

    - name: Compile Code
      run: ./gradlew build
      working-directory: backend

    # - name: Run Unit Tests
    # - name: Run Narrow Integration Tests
    # - name: Run Component Tests
    # - name: Run Contract Tests
    # - name: Run Linter
    # - name: Run Code Analysis

    - name: Build and Push Artifact
      id: publish
      uses: optivem/actions/publish-docker-image@v1
      with:
        working-directory: backend
        image-name: backend
        registry: ghcr.io
        registry-username: ${{ github.actor }}
        image-namespace: ${{ github.repository }}
        image-latest-tag: latest
        commit-sha: ${{ github.sha }}
        dockerfile: Dockerfile
      env:
        REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  summary:
    needs: build
    runs-on: ubuntu-latest
    if: always()

    steps:
      
    - name: Commit Stage Summary
      uses: optivem/actions/summarize-commit-stage@v1
      with:
        stage-result: ${{ needs.build.result }}
        success-artifact-url: ${{ needs.build.outputs.image-digest-url }}
